SRC=./src/
thread: thread.o
	$(SRC)thread
thread.o: $(SRC)thread.cpp
	g++ -pthread -o $(SRC)thread $(SRC)thread.cpp

thread2: thread2.o
	$(SRC)thread2
thread2.o: $(SRC)thread02.cpp
	g++ -pthread -o $(SRC)thread2 $(SRC)thread02.cpp
